### ISSUE TITLE
Panel Vertical Positiong

### ISSUE THREAD

**Issue by fsalaysay** [fsalaysay/SundayClub#1]
# Vertical centering of login Panel

Currently, html structure is as follows: 

```html
    <div class="wrapper"> <!-- THIS has the square with shadow set as background -->
      <div class="col-md-3 col-sm-3 col-md-push-9 col-sm-push-9 panel-area"> <!-- bootstrap default classes -->
        <a href="" class="logo">
          <img src="../images/logo.png" alt="DearBrian Logo">
        </a>
        <h2 class="panel-section-label">Login</h2>
        <form>
          <div class="form-group">
            <input type="text" class="form-control" id="username" placeholder="Username">
            <input type="password" class="form-control" id="password" placeholder="Password">
            <button type="button" class="btn btn-default">Login</button>
            <div class="checkbox">
              <label>
                <input type="checkbox"><span class="remember">Remember Me</span></input>
              </label>
            </div>
          </div>
        </form>
        <span class="call-to-action">Don't have an account? <a href="#">Sign up</a> here!</span>
      </div>
      <div class="col-md-9 col-sm-9 col-md-pull-3 col-sm-pull-3 form-area">
      </div>
    </div>
```
and CSS (written in SCSS) is as follows: 

```scss
.panel-area {
    height: 100%;
    // THIS creates the square background with shadow
    background: url(../images/box.png) no-repeat center center;
    background-size: 100% 420px;
    text-align: center;

    padding: 10px 10px;

    .logo {
      width: 100%;
      margin: 0 0;
      padding: 0 0;

      img {
        display: block;
        width: 75%;
        margin: 10px auto;
      }

      button {
        text-align: left;
      }

      .checkbox {
        padding: 0 0;
        margin: 0 0;

        .remember {
          font-size: 0.5em;
        }
      }
    }

    .panel-section-label {
      margin: 0 0; 
      padding: 0 0;
      text-align: center;
      padding-bottom: 10px;
    }

    .form-control {
      width: 70%;
      margin: 10px auto;
    }

    .call-to-action {
      display: block;
      width: 75%;
      margin: 0 auto;
      font-size: 0.8em;

      a {
        font-weight: bold;
      }
    }
  }
```
Some things to consider
- doing ```height: 100%``` does not work because of doctype incompatibility
- setting height to static value will make it inflexible
- using ```translate(%)``` will make it inflexible too when resized

### Possible fix:
- separate ```div``` with background and ```div``` with contents then align
- separate ```img``` and ```div``` with contents then align absolutely (might be a little buggy?)
